// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: amm/packet.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AmmPacketData struct {
	// Types that are valid to be assigned to Packet:
	//	*AmmPacketData_NoData
	//	*AmmPacketData_RemoveLiquidityPacket
	//	*AmmPacketData_AddLiquidityPacket
	//	*AmmPacketData_CreatePoolPacket
	Packet isAmmPacketData_Packet `protobuf_oneof:"packet"`
}

func (m *AmmPacketData) Reset()         { *m = AmmPacketData{} }
func (m *AmmPacketData) String() string { return proto.CompactTextString(m) }
func (*AmmPacketData) ProtoMessage()    {}
func (*AmmPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c32ba42bae7bc3, []int{0}
}
func (m *AmmPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AmmPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AmmPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AmmPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AmmPacketData.Merge(m, src)
}
func (m *AmmPacketData) XXX_Size() int {
	return m.Size()
}
func (m *AmmPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_AmmPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_AmmPacketData proto.InternalMessageInfo

type isAmmPacketData_Packet interface {
	isAmmPacketData_Packet()
	MarshalTo([]byte) (int, error)
	Size() int
}

type AmmPacketData_NoData struct {
	NoData *NoData `protobuf:"bytes,1,opt,name=noData,proto3,oneof" json:"noData,omitempty"`
}
type AmmPacketData_RemoveLiquidityPacket struct {
	RemoveLiquidityPacket *RemoveLiquidityPacketData `protobuf:"bytes,4,opt,name=removeLiquidityPacket,proto3,oneof" json:"removeLiquidityPacket,omitempty"`
}
type AmmPacketData_AddLiquidityPacket struct {
	AddLiquidityPacket *AddLiquidityPacketData `protobuf:"bytes,3,opt,name=addLiquidityPacket,proto3,oneof" json:"addLiquidityPacket,omitempty"`
}
type AmmPacketData_CreatePoolPacket struct {
	CreatePoolPacket *CreatePoolPacketData `protobuf:"bytes,2,opt,name=createPoolPacket,proto3,oneof" json:"createPoolPacket,omitempty"`
}

func (*AmmPacketData_NoData) isAmmPacketData_Packet()                {}
func (*AmmPacketData_RemoveLiquidityPacket) isAmmPacketData_Packet() {}
func (*AmmPacketData_AddLiquidityPacket) isAmmPacketData_Packet()    {}
func (*AmmPacketData_CreatePoolPacket) isAmmPacketData_Packet()      {}

func (m *AmmPacketData) GetPacket() isAmmPacketData_Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *AmmPacketData) GetNoData() *NoData {
	if x, ok := m.GetPacket().(*AmmPacketData_NoData); ok {
		return x.NoData
	}
	return nil
}

func (m *AmmPacketData) GetRemoveLiquidityPacket() *RemoveLiquidityPacketData {
	if x, ok := m.GetPacket().(*AmmPacketData_RemoveLiquidityPacket); ok {
		return x.RemoveLiquidityPacket
	}
	return nil
}

func (m *AmmPacketData) GetAddLiquidityPacket() *AddLiquidityPacketData {
	if x, ok := m.GetPacket().(*AmmPacketData_AddLiquidityPacket); ok {
		return x.AddLiquidityPacket
	}
	return nil
}

func (m *AmmPacketData) GetCreatePoolPacket() *CreatePoolPacketData {
	if x, ok := m.GetPacket().(*AmmPacketData_CreatePoolPacket); ok {
		return x.CreatePoolPacket
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AmmPacketData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AmmPacketData_NoData)(nil),
		(*AmmPacketData_RemoveLiquidityPacket)(nil),
		(*AmmPacketData_AddLiquidityPacket)(nil),
		(*AmmPacketData_CreatePoolPacket)(nil),
	}
}

type NoData struct {
}

func (m *NoData) Reset()         { *m = NoData{} }
func (m *NoData) String() string { return proto.CompactTextString(m) }
func (*NoData) ProtoMessage()    {}
func (*NoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c32ba42bae7bc3, []int{1}
}
func (m *NoData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NoData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoData.Merge(m, src)
}
func (m *NoData) XXX_Size() int {
	return m.Size()
}
func (m *NoData) XXX_DiscardUnknown() {
	xxx_messageInfo_NoData.DiscardUnknown(m)
}

var xxx_messageInfo_NoData proto.InternalMessageInfo

// CreatePoolPacketData defines a struct for the packet payload
type CreatePoolPacketData struct {
	PoolParam  string `protobuf:"bytes,1,opt,name=poolParam,proto3" json:"poolParam,omitempty"`
	PoolAssets string `protobuf:"bytes,2,opt,name=poolAssets,proto3" json:"poolAssets,omitempty"`
}

func (m *CreatePoolPacketData) Reset()         { *m = CreatePoolPacketData{} }
func (m *CreatePoolPacketData) String() string { return proto.CompactTextString(m) }
func (*CreatePoolPacketData) ProtoMessage()    {}
func (*CreatePoolPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c32ba42bae7bc3, []int{2}
}
func (m *CreatePoolPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreatePoolPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreatePoolPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreatePoolPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePoolPacketData.Merge(m, src)
}
func (m *CreatePoolPacketData) XXX_Size() int {
	return m.Size()
}
func (m *CreatePoolPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePoolPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePoolPacketData proto.InternalMessageInfo

func (m *CreatePoolPacketData) GetPoolParam() string {
	if m != nil {
		return m.PoolParam
	}
	return ""
}

func (m *CreatePoolPacketData) GetPoolAssets() string {
	if m != nil {
		return m.PoolAssets
	}
	return ""
}

// CreatePoolPacketAck defines a struct for the packet acknowledgment
type CreatePoolPacketAck struct {
	PoolId int32 `protobuf:"varint,1,opt,name=poolId,proto3" json:"poolId,omitempty"`
}

func (m *CreatePoolPacketAck) Reset()         { *m = CreatePoolPacketAck{} }
func (m *CreatePoolPacketAck) String() string { return proto.CompactTextString(m) }
func (*CreatePoolPacketAck) ProtoMessage()    {}
func (*CreatePoolPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c32ba42bae7bc3, []int{3}
}
func (m *CreatePoolPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreatePoolPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreatePoolPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreatePoolPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePoolPacketAck.Merge(m, src)
}
func (m *CreatePoolPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *CreatePoolPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePoolPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePoolPacketAck proto.InternalMessageInfo

func (m *CreatePoolPacketAck) GetPoolId() int32 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

// AddLiquidityPacketData defines a struct for the packet payload
type AddLiquidityPacketData struct {
	AmountVela  string `protobuf:"bytes,1,opt,name=amountVela,proto3" json:"amountVela,omitempty"`
	AmountOther string `protobuf:"bytes,2,opt,name=amountOther,proto3" json:"amountOther,omitempty"`
}

func (m *AddLiquidityPacketData) Reset()         { *m = AddLiquidityPacketData{} }
func (m *AddLiquidityPacketData) String() string { return proto.CompactTextString(m) }
func (*AddLiquidityPacketData) ProtoMessage()    {}
func (*AddLiquidityPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c32ba42bae7bc3, []int{4}
}
func (m *AddLiquidityPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddLiquidityPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddLiquidityPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddLiquidityPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddLiquidityPacketData.Merge(m, src)
}
func (m *AddLiquidityPacketData) XXX_Size() int {
	return m.Size()
}
func (m *AddLiquidityPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_AddLiquidityPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_AddLiquidityPacketData proto.InternalMessageInfo

func (m *AddLiquidityPacketData) GetAmountVela() string {
	if m != nil {
		return m.AmountVela
	}
	return ""
}

func (m *AddLiquidityPacketData) GetAmountOther() string {
	if m != nil {
		return m.AmountOther
	}
	return ""
}

// AddLiquidityPacketAck defines a struct for the packet acknowledgment
type AddLiquidityPacketAck struct {
	AmountShares string `protobuf:"bytes,1,opt,name=amountShares,proto3" json:"amountShares,omitempty"`
}

func (m *AddLiquidityPacketAck) Reset()         { *m = AddLiquidityPacketAck{} }
func (m *AddLiquidityPacketAck) String() string { return proto.CompactTextString(m) }
func (*AddLiquidityPacketAck) ProtoMessage()    {}
func (*AddLiquidityPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c32ba42bae7bc3, []int{5}
}
func (m *AddLiquidityPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddLiquidityPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddLiquidityPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddLiquidityPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddLiquidityPacketAck.Merge(m, src)
}
func (m *AddLiquidityPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *AddLiquidityPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_AddLiquidityPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_AddLiquidityPacketAck proto.InternalMessageInfo

func (m *AddLiquidityPacketAck) GetAmountShares() string {
	if m != nil {
		return m.AmountShares
	}
	return ""
}

// RemoveLiquidityPacketData defines a struct for the packet payload
type RemoveLiquidityPacketData struct {
	AmountShare string `protobuf:"bytes,1,opt,name=amountShare,proto3" json:"amountShare,omitempty"`
	AmountOther string `protobuf:"bytes,2,opt,name=amountOther,proto3" json:"amountOther,omitempty"`
}

func (m *RemoveLiquidityPacketData) Reset()         { *m = RemoveLiquidityPacketData{} }
func (m *RemoveLiquidityPacketData) String() string { return proto.CompactTextString(m) }
func (*RemoveLiquidityPacketData) ProtoMessage()    {}
func (*RemoveLiquidityPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c32ba42bae7bc3, []int{6}
}
func (m *RemoveLiquidityPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoveLiquidityPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemoveLiquidityPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RemoveLiquidityPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveLiquidityPacketData.Merge(m, src)
}
func (m *RemoveLiquidityPacketData) XXX_Size() int {
	return m.Size()
}
func (m *RemoveLiquidityPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveLiquidityPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveLiquidityPacketData proto.InternalMessageInfo

func (m *RemoveLiquidityPacketData) GetAmountShare() string {
	if m != nil {
		return m.AmountShare
	}
	return ""
}

func (m *RemoveLiquidityPacketData) GetAmountOther() string {
	if m != nil {
		return m.AmountOther
	}
	return ""
}

// RemoveLiquidityPacketAck defines a struct for the packet acknowledgment
type RemoveLiquidityPacketAck struct {
	AmountVela string `protobuf:"bytes,1,opt,name=amountVela,proto3" json:"amountVela,omitempty"`
}

func (m *RemoveLiquidityPacketAck) Reset()         { *m = RemoveLiquidityPacketAck{} }
func (m *RemoveLiquidityPacketAck) String() string { return proto.CompactTextString(m) }
func (*RemoveLiquidityPacketAck) ProtoMessage()    {}
func (*RemoveLiquidityPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7c32ba42bae7bc3, []int{7}
}
func (m *RemoveLiquidityPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoveLiquidityPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemoveLiquidityPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RemoveLiquidityPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveLiquidityPacketAck.Merge(m, src)
}
func (m *RemoveLiquidityPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *RemoveLiquidityPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveLiquidityPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveLiquidityPacketAck proto.InternalMessageInfo

func (m *RemoveLiquidityPacketAck) GetAmountVela() string {
	if m != nil {
		return m.AmountVela
	}
	return ""
}

func init() {
	proto.RegisterType((*AmmPacketData)(nil), "lostak.vela.amm.AmmPacketData")
	proto.RegisterType((*NoData)(nil), "lostak.vela.amm.NoData")
	proto.RegisterType((*CreatePoolPacketData)(nil), "lostak.vela.amm.CreatePoolPacketData")
	proto.RegisterType((*CreatePoolPacketAck)(nil), "lostak.vela.amm.CreatePoolPacketAck")
	proto.RegisterType((*AddLiquidityPacketData)(nil), "lostak.vela.amm.AddLiquidityPacketData")
	proto.RegisterType((*AddLiquidityPacketAck)(nil), "lostak.vela.amm.AddLiquidityPacketAck")
	proto.RegisterType((*RemoveLiquidityPacketData)(nil), "lostak.vela.amm.RemoveLiquidityPacketData")
	proto.RegisterType((*RemoveLiquidityPacketAck)(nil), "lostak.vela.amm.RemoveLiquidityPacketAck")
}

func init() { proto.RegisterFile("amm/packet.proto", fileDescriptor_a7c32ba42bae7bc3) }

var fileDescriptor_a7c32ba42bae7bc3 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x6b, 0xdb, 0x30,
	0x1c, 0xc5, 0xed, 0x6c, 0x33, 0xc9, 0x3f, 0x1b, 0x0b, 0xda, 0x92, 0x65, 0x30, 0x4c, 0x10, 0x8c,
	0x8d, 0xc1, 0x6c, 0xb6, 0xdd, 0xb6, 0x5d, 0x9c, 0xed, 0xb0, 0xc1, 0x58, 0x83, 0x53, 0x0a, 0xcd,
	0xa5, 0x28, 0xb6, 0x68, 0x4c, 0xac, 0xc8, 0xb5, 0x95, 0xd0, 0x7c, 0x8b, 0x7e, 0xac, 0x1e, 0x73,
	0xec, 0x31, 0x24, 0x5f, 0xa4, 0x48, 0x16, 0xc4, 0xb5, 0x5d, 0xda, 0x5b, 0xf4, 0xf2, 0xfe, 0xbf,
	0xf7, 0xfc, 0x47, 0x82, 0x0e, 0x61, 0xcc, 0x4d, 0x48, 0x30, 0xa7, 0xc2, 0x49, 0x52, 0x2e, 0x38,
	0x7a, 0x19, 0xf3, 0x4c, 0x90, 0xb9, 0xb3, 0xa2, 0x31, 0x71, 0x08, 0x63, 0x78, 0xdb, 0x80, 0x17,
	0x1e, 0x63, 0x23, 0x65, 0xfa, 0x4d, 0x04, 0x41, 0x5f, 0xc0, 0x5a, 0x70, 0xf9, 0xab, 0x6f, 0x0e,
	0xcc, 0x8f, 0xed, 0xaf, 0x6f, 0x9c, 0xd2, 0x8c, 0xf3, 0x5f, 0xfd, 0xfd, 0xc7, 0xf0, 0xb5, 0x11,
	0x4d, 0xa1, 0x9b, 0x52, 0xc6, 0x57, 0xf4, 0x5f, 0x74, 0xb1, 0x8c, 0xc2, 0x48, 0xac, 0x73, 0x5e,
	0xff, 0xa9, 0x22, 0x7c, 0xaa, 0x10, 0xfc, 0x3a, 0xb7, 0x86, 0xd6, 0xa3, 0xd0, 0x29, 0x20, 0x12,
	0x86, 0xe5, 0x80, 0x27, 0x2a, 0xe0, 0x43, 0x25, 0xc0, 0xab, 0x58, 0x35, 0xbd, 0x06, 0x82, 0xc6,
	0xd0, 0x09, 0x52, 0x4a, 0x04, 0x1d, 0x71, 0x1e, 0x6b, 0x70, 0x43, 0x81, 0xdf, 0x57, 0xc0, 0xbf,
	0x4a, 0x46, 0x8d, 0xad, 0x00, 0x86, 0x4d, 0xb0, 0xf2, 0xcd, 0xe3, 0x26, 0x58, 0xf9, 0xc6, 0xf0,
	0x31, 0xbc, 0xae, 0x9b, 0x47, 0xef, 0xa0, 0x95, 0x28, 0x25, 0x25, 0x4c, 0x6d, 0xbd, 0xe5, 0x1f,
	0x04, 0x64, 0x03, 0xc8, 0x83, 0x97, 0x65, 0x54, 0x64, 0xaa, 0x58, 0xcb, 0x2f, 0x28, 0xf8, 0x33,
	0xbc, 0x2a, 0x53, 0xbd, 0x60, 0x8e, 0x7a, 0x60, 0x49, 0xd3, 0xdf, 0x50, 0x11, 0x9f, 0xf9, 0xfa,
	0x84, 0x27, 0xd0, 0xab, 0xdf, 0x8e, 0x0c, 0x22, 0x8c, 0x2f, 0x17, 0xe2, 0x84, 0xc6, 0x44, 0xf7,
	0x28, 0x28, 0x68, 0x00, 0xed, 0xfc, 0x74, 0x24, 0x66, 0x34, 0xd5, 0x4d, 0x8a, 0x12, 0xfe, 0x01,
	0xdd, 0x2a, 0x5b, 0x96, 0xc1, 0xf0, 0x3c, 0xf7, 0x8d, 0x67, 0x24, 0xa5, 0x99, 0x86, 0xdf, 0xd1,
	0xf0, 0x19, 0xbc, 0xbd, 0xf7, 0x5e, 0x1c, 0xb2, 0x95, 0x59, 0xcf, 0x17, 0xa5, 0x47, 0xb4, 0xfb,
	0x0e, 0xfd, 0xda, 0x00, 0x59, 0xf0, 0x81, 0x6f, 0x1f, 0xfe, 0xbc, 0xde, 0xd9, 0xe6, 0x66, 0x67,
	0x9b, 0xdb, 0x9d, 0x6d, 0x5e, 0xed, 0x6d, 0x63, 0xb3, 0xb7, 0x8d, 0x9b, 0xbd, 0x6d, 0x4c, 0xf0,
	0x79, 0x24, 0x66, 0xcb, 0xa9, 0x13, 0x70, 0xe6, 0xe6, 0xb7, 0xc5, 0x95, 0x13, 0xee, 0xa5, 0x2b,
	0x5f, 0x9f, 0x58, 0x27, 0x34, 0x9b, 0x5a, 0xea, 0xf5, 0x7d, 0xbb, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x20, 0x8f, 0x98, 0x94, 0x91, 0x03, 0x00, 0x00,
}

func (m *AmmPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AmmPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AmmPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Packet != nil {
		{
			size := m.Packet.Size()
			i -= size
			if _, err := m.Packet.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *AmmPacketData_NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AmmPacketData_NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.NoData != nil {
		{
			size, err := m.NoData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *AmmPacketData_CreatePoolPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AmmPacketData_CreatePoolPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CreatePoolPacket != nil {
		{
			size, err := m.CreatePoolPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *AmmPacketData_AddLiquidityPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AmmPacketData_AddLiquidityPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.AddLiquidityPacket != nil {
		{
			size, err := m.AddLiquidityPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *AmmPacketData_RemoveLiquidityPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AmmPacketData_RemoveLiquidityPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.RemoveLiquidityPacket != nil {
		{
			size, err := m.RemoveLiquidityPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *NoData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *CreatePoolPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatePoolPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreatePoolPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PoolAssets) > 0 {
		i -= len(m.PoolAssets)
		copy(dAtA[i:], m.PoolAssets)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.PoolAssets)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PoolParam) > 0 {
		i -= len(m.PoolParam)
		copy(dAtA[i:], m.PoolParam)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.PoolParam)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreatePoolPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatePoolPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreatePoolPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PoolId != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AddLiquidityPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddLiquidityPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddLiquidityPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AmountOther) > 0 {
		i -= len(m.AmountOther)
		copy(dAtA[i:], m.AmountOther)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.AmountOther)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AmountVela) > 0 {
		i -= len(m.AmountVela)
		copy(dAtA[i:], m.AmountVela)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.AmountVela)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AddLiquidityPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddLiquidityPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddLiquidityPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AmountShares) > 0 {
		i -= len(m.AmountShares)
		copy(dAtA[i:], m.AmountShares)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.AmountShares)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RemoveLiquidityPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoveLiquidityPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RemoveLiquidityPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AmountOther) > 0 {
		i -= len(m.AmountOther)
		copy(dAtA[i:], m.AmountOther)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.AmountOther)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AmountShare) > 0 {
		i -= len(m.AmountShare)
		copy(dAtA[i:], m.AmountShare)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.AmountShare)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RemoveLiquidityPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoveLiquidityPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RemoveLiquidityPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AmountVela) > 0 {
		i -= len(m.AmountVela)
		copy(dAtA[i:], m.AmountVela)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.AmountVela)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AmmPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Packet != nil {
		n += m.Packet.Size()
	}
	return n
}

func (m *AmmPacketData_NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NoData != nil {
		l = m.NoData.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *AmmPacketData_CreatePoolPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CreatePoolPacket != nil {
		l = m.CreatePoolPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *AmmPacketData_AddLiquidityPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AddLiquidityPacket != nil {
		l = m.AddLiquidityPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *AmmPacketData_RemoveLiquidityPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RemoveLiquidityPacket != nil {
		l = m.RemoveLiquidityPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *CreatePoolPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolParam)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.PoolAssets)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *CreatePoolPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovPacket(uint64(m.PoolId))
	}
	return n
}

func (m *AddLiquidityPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AmountVela)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.AmountOther)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *AddLiquidityPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AmountShares)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *RemoveLiquidityPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AmountShare)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.AmountOther)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *RemoveLiquidityPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AmountVela)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AmmPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AmmPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AmmPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NoData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &AmmPacketData_NoData{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatePoolPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CreatePoolPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &AmmPacketData_CreatePoolPacket{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddLiquidityPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &AddLiquidityPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &AmmPacketData_AddLiquidityPacket{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoveLiquidityPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &RemoveLiquidityPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &AmmPacketData_RemoveLiquidityPacket{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NoData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NoData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NoData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreatePoolPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatePoolPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatePoolPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolParam", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolParam = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolAssets", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolAssets = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreatePoolPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatePoolPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatePoolPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddLiquidityPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddLiquidityPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddLiquidityPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountVela", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AmountVela = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountOther", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AmountOther = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddLiquidityPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddLiquidityPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddLiquidityPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AmountShares = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemoveLiquidityPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoveLiquidityPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoveLiquidityPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AmountShare = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountOther", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AmountOther = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemoveLiquidityPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoveLiquidityPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoveLiquidityPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountVela", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AmountVela = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
